import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const STEP=2,BASE_Y=-2,MAX_LAYER=4,SNAP_PX=72;
const DIRECTIONS=[new THREE.Vector3(STEP,0,0),new THREE.Vector3(-STEP,0,0),new THREE.Vector3(0,0,STEP),new THREE.Vector3(0,0,-STEP),new THREE.Vector3(0,STEP,0),new THREE.Vector3(0,-STEP,0)];
const wrap=document.getElementById('canvasWrap');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xedf4fb);
const camera=new THREE.PerspectiveCamera(43,1,.1,1000);camera.position.set(9,7.5,11);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;wrap.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x72879c,2.25));const sun=new THREE.DirectionalLight(0xffffff,2.05);sun.position.set(8,13,9);sun.castShadow=true;scene.add(sun);
const grid=new THREE.GridHelper(24,12,0x8ca4c0,0xc9d7e7);grid.position.y=BASE_Y;scene.add(grid);const floor=new THREE.Mesh(new THREE.PlaneGeometry(24,24),new THREE.ShadowMaterial({color:0x0f172a,opacity:.07}));floor.rotation.x=-Math.PI/2;floor.position.y=BASE_Y+.01;floor.receiveShadow=true;scene.add(floor);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.target.set(0,-.4,0);controls.minDistance=5;controls.maxDistance=28;
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),workPlane=new THREE.Plane(),workPoint=new THREE.Vector3();
const vertexGeo=new THREE.SphereGeometry(.29,28,20),edgeGeo=new THREE.CylinderGeometry(.085,.085,1,18);
const vertexMat=()=>new THREE.MeshStandardMaterial({color:0x315eea,roughness:.27,emissive:0x000000});
const edgeMat=()=>new THREE.MeshStandardMaterial({color:0x1f2937,roughness:.33,emissive:0x000000});
const vertices=[],edges=[];let nextVertexId=1,nextEdgeId=1,currentLayer=0,selected=null,toolDrag=null,objectDrag=null,toastTimer;
const guideGroup=new THREE.Group();scene.add(guideGroup);
const ui={vc:document.getElementById('vertexCount'),ec:document.getElementById('edgeCount'),selection:document.getElementById('selection'),selectionName:document.getElementById('selectionName'),toast:document.getElementById('toast'),ghost:document.getElementById('dragGhost'),ghostIcon:document.getElementById('ghostIcon'),ghostText:document.getElementById('ghostText'),layerValue:document.getElementById('layerValue'),hint:document.getElementById('hint')};

const snapGroup=new THREE.Group();scene.add(snapGroup);
const haloMat=new THREE.MeshBasicMaterial({color:0x20c77b,transparent:true,opacity:.42,depthWrite:false});
const haloGeo=new THREE.SphereGeometry(.43,22,16);
const snapHaloA=new THREE.Mesh(haloGeo,haloMat.clone()),snapHaloB=new THREE.Mesh(haloGeo,haloMat.clone());snapGroup.add(snapHaloA,snapHaloB);snapHaloA.visible=snapHaloB.visible=false;
const snapEdge=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,1,12),new THREE.MeshBasicMaterial({color:0x18b36e,transparent:true,opacity:.68,depthWrite:false}));snapEdge.visible=false;snapGroup.add(snapEdge);
const previewVertex=new THREE.Mesh(vertexGeo,new THREE.MeshStandardMaterial({color:0x20c77b,transparent:true,opacity:.72,roughness:.25}));previewVertex.visible=false;scene.add(previewVertex);

function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function showToast(text){clearTimeout(toastTimer);ui.toast.textContent=text;ui.toast.classList.add('show');toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1700)}
function setHint(text,isSnap=false){ui.hint.textContent=text;ui.hint.classList.toggle('snap',isSnap);ui.ghost.classList.toggle('snap',isSnap)}
function setPointer(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.x=(x-r.left)/r.width*2-1;pointer.y=-(y-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera)}
function worldToScreen(p){const q=p.clone().project(camera),r=renderer.domElement.getBoundingClientRect();return{x:r.left+(q.x+1)*.5*r.width,y:r.top+(-q.y+1)*.5*r.height}}
function screenDistance(p,x,y){const s=worldToScreen(p);return Math.hypot(s.x-x,s.y-y)}
function layerY(layer=currentLayer){return BASE_Y+layer*STEP}
function pointOnLayer(x,y,layer=currentLayer){setPointer(x,y);workPlane.set(new THREE.Vector3(0,1,0),-layerY(layer));if(!raycaster.ray.intersectPlane(workPlane,workPoint))return null;return new THREE.Vector3(Math.round(workPoint.x/STEP)*STEP,layerY(layer),Math.round(workPoint.z/STEP)*STEP)}
function key(p){return `${Math.round(p.x/STEP)},${Math.round((p.y-BASE_Y)/STEP)},${Math.round(p.z/STEP)}`}
function findVertexAt(p,except=null){const k=key(p);return vertices.find(v=>v!==except&&key(v.position)===k)||null}
function pickObject(x,y){setPointer(x,y);return raycaster.intersectObjects([...vertices,...edges.map(e=>e.mesh)],false)[0]?.object||null}
function axisAligned(a,b){const dx=Math.abs(a.x-b.x)>.01,dy=Math.abs(a.y-b.y)>.01,dz=Math.abs(a.z-b.z)>.01;return Number(dx)+Number(dy)+Number(dz)===1}
function edgeExists(a,b,except=null){return edges.some(e=>e!==except&&((e.a===a&&e.b===b)||(e.a===b&&e.b===a)))}
function connectedEdges(v){return edges.filter(e=>e.a===v||e.b===v)}
function updateUI(){ui.vc.textContent=vertices.length;ui.ec.textContent=edges.length;ui.layerValue.textContent=currentLayer+1}
function createVertex(pos){const existing=findVertexAt(pos);if(existing)return existing;const m=new THREE.Mesh(vertexGeo,vertexMat());m.position.copy(pos);m.castShadow=true;m.userData={kind:'vertex',id:nextVertexId++};scene.add(m);vertices.push(m);updateUI();return m}
function updateEdge(e){const a=e.a.position,b=e.b.position,d=b.clone().sub(a),len=Math.max(d.length(),.01);e.mesh.position.copy(a).add(b).multiplyScalar(.5);e.mesh.scale.set(1,len,1);e.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize())}
function createEdge(a,b){if(!a||!b||a===b||!axisAligned(a.position,b.position)||edgeExists(a,b))return null;const m=new THREE.Mesh(edgeGeo,edgeMat());m.castShadow=true;m.userData={kind:'edge'};const e={id:nextEdgeId++,a,b,mesh:m};m.userData.edge=e;scene.add(m);edges.push(e);updateEdge(e);updateUI();return e}
function removeEdge(e){scene.remove(e.mesh);const i=edges.indexOf(e);if(i>=0)edges.splice(i,1)}
function removeDuplicateEdges(){for(let i=edges.length-1;i>=0;i--){const e=edges[i];if(e.a===e.b){removeEdge(e);continue}for(let j=0;j<i;j++){const x=edges[j];if((x.a===e.a&&x.b===e.b)||(x.a===e.b&&x.b===e.a)){removeEdge(e);break}}}}
function mergeVertices(source,target){if(source===target)return target;for(const e of edges){if(e.a===source)e.a=target;if(e.b===source)e.b=target}removeDuplicateEdges();scene.remove(source);const i=vertices.indexOf(source);if(i>=0)vertices.splice(i,1);updateUI();return target}
function clearSnapVisual(){snapHaloA.visible=snapHaloB.visible=snapEdge.visible=previewVertex.visible=false;setHint('拖動頂點或稜；綠色位置代表放手後會自動連接',false)}
function setGhostEdge(a,b){const d=b.clone().sub(a),len=Math.max(d.length(),.01);snapEdge.position.copy(a).add(b).multiplyScalar(.5);snapEdge.scale.set(1,len,1);snapEdge.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());snapEdge.visible=true}
function showVertexSnap(candidate){clearSnapVisual();previewVertex.position.copy(candidate.position);previewVertex.visible=true;snapHaloA.position.copy(candidate.position);snapHaloA.visible=true;if(candidate.source){snapHaloB.position.copy(candidate.source.position);snapHaloB.visible=true;setGhostEdge(candidate.source.position,candidate.position)}setHint(candidate.merge?'放手後會合併到綠色頂點':'放手後會自動吸附及連接',true)}
function showEdgeSnap(candidate){clearSnapVisual();snapHaloA.position.copy(candidate.aPos);snapHaloB.position.copy(candidate.bPos);snapHaloA.visible=snapHaloB.visible=true;setGhostEdge(candidate.aPos,candidate.bPos);setHint('放手後稜會自動接到綠色位置',true)}

function validVertexPosition(vertex,pos,mergeTarget=null){if(pos.y<BASE_Y||pos.y>layerY(MAX_LAYER-1))return false;const occupied=findVertexAt(pos,vertex);if(occupied&&occupied!==mergeTarget)return false;for(const e of connectedEdges(vertex)){const n=e.a===vertex?e.b:e.a;if(mergeTarget&&n===mergeTarget)continue;if(!axisAligned(pos,n.position))return false}return true}
function candidateForVertex(vertex,x,y,layer){let best=null;
  for(const target of vertices){if(target===vertex)continue;const d=screenDistance(target.position,x,y);if(d<SNAP_PX&&validVertexPosition(vertex,target.position,target)&&(!best||d<best.distance))best={type:'merge',merge:target,position:target.position.clone(),distance:d};}
  for(const source of vertices){if(source===vertex)continue;for(const dir of DIRECTIONS){const p=source.position.clone().add(dir);if(!validVertexPosition(vertex,p))continue;const d=screenDistance(p,x,y);if(d<SNAP_PX&&(!best||d<best.distance))best={type:'connect',source,position:p,distance:d};}}
  const free=pointOnLayer(x,y,layer);if(free&&validVertexPosition(vertex,free)){const d=screenDistance(free,x,y);if(!best||d<best.distance)best={type:'free',position:free,distance:d};}
  return best;
}
function candidateForNewVertex(x,y){let best=null;
  for(const target of vertices){const d=screenDistance(target.position,x,y);if(d<SNAP_PX&&(!best||d<best.distance))best={type:'existing',existing:target,position:target.position.clone(),distance:d};}
  for(const source of vertices){for(const dir of DIRECTIONS){const p=source.position.clone().add(dir);const occupied=findVertexAt(p);if(occupied)continue;const d=screenDistance(p,x,y);if(d<SNAP_PX&&(!best||d<best.distance))best={type:'connect',source,position:p,distance:d};}}
  const free=pointOnLayer(x,y,currentLayer);if(free){const existing=findVertexAt(free);const d=screenDistance(free,x,y);if(!best||d<best.distance)best=existing?{type:'existing',existing,position:existing.position.clone(),distance:d}:{type:'free',position:free,distance:d};}
  return best;
}
function potentialSegments(exceptEdge=null){const list=[];
  for(let i=0;i<vertices.length;i++)for(let j=i+1;j<vertices.length;j++){const a=vertices[i],b=vertices[j];if(axisAligned(a.position,b.position)&&!edgeExists(a,b,exceptEdge))list.push({a,b,aPos:a.position.clone(),bPos:b.position.clone(),existingPair:true});}
  for(const a of vertices){for(const dir of DIRECTIONS){const p=a.position.clone().add(dir),b=findVertexAt(p);if(b){if(!edgeExists(a,b,exceptEdge))list.push({a,b,aPos:a.position.clone(),bPos:b.position.clone(),existingPair:true});}else list.push({a,b:null,aPos:a.position.clone(),bPos:p,existingPair:false});}}
  return list;
}
function candidateForEdge(x,y,exceptEdge=null){let best=null;for(const c of potentialSegments(exceptEdge)){const mid=c.aPos.clone().add(c.bPos).multiplyScalar(.5),d=screenDistance(mid,x,y);if(d<100&&(!best||d<best.distance))best={...c,distance:d};}
  if(best)return best;const p=pointOnLayer(x,y,currentLayer);if(!p)return null;let aPos=p.clone(),bPos=p.clone().add(new THREE.Vector3(STEP,0,0));let a=findVertexAt(aPos),b=findVertexAt(bPos);return{a,b,aPos,bPos,distance:999,free:true};
}

function clearSelection(){if(selected?.type==='vertex'){selected.item.material.emissive.setHex(0);selected.item.scale.setScalar(1)}if(selected?.type==='edge'){selected.item.mesh.material.emissive.setHex(0);selected.item.mesh.scale.x=1;selected.item.mesh.scale.z=1}selected=null;ui.selection.classList.remove('show')}
function selectVertex(v){clearSelection();selected={type:'vertex',item:v};v.material.emissive.setHex(0x9a5b00);v.scale.setScalar(1.17);ui.selectionName.textContent=`頂點 ${v.userData.id}`;ui.selection.classList.add('show');document.getElementById('moveUpBtn').style.display='block';document.getElementById('moveDownBtn').style.display='block'}
function selectEdge(e){clearSelection();selected={type:'edge',item:e};e.mesh.material.emissive.setHex(0x9a5b00);e.mesh.scale.x=1.25;e.mesh.scale.z=1.25;ui.selectionName.textContent=`稜 ${e.id}`;ui.selection.classList.add('show');document.getElementById('moveUpBtn').style.display='none';document.getElementById('moveDownBtn').style.display='none'}
function deleteSelected(){if(!selected)return;if(selected.type==='edge'){removeEdge(selected.item);clearSelection();updateUI();showToast('已刪除稜');return}const v=selected.item;for(const e of [...connectedEdges(v)])removeEdge(e);scene.remove(v);vertices.splice(vertices.indexOf(v),1);clearSelection();updateUI();showToast('已刪除頂點及相連稜')}
function moveSelectedLayer(delta){if(selected?.type!=='vertex')return;const v=selected.item,p=v.position.clone();p.y+=delta*STEP;if(!validVertexPosition(v,p)){showToast('這個位置會令稜變斜或重疊');return}v.position.copy(p);currentLayer=Math.round((p.y-BASE_Y)/STEP);updateUI();showToast(`頂點已移到第 ${currentLayer+1} 層`)}
function resetView(){camera.position.set(9,7.5,11);controls.target.set(0,-.4,0);controls.update();showToast('已重設視角')}
function clearAll(){clearSelection();clearSnapVisual();vertices.forEach(v=>scene.remove(v));edges.forEach(e=>scene.remove(e.mesh));vertices.length=0;edges.length=0;nextVertexId=1;nextEdgeId=1;updateUI()}

function moveGhost(x,y){ui.ghost.style.left=x+'px';ui.ghost.style.top=y+'px'}
function startToolDrag(e,type){e.preventDefault();toolDrag={type,candidate:null};controls.enabled=false;ui.ghost.classList.add('show');ui.ghostIcon.className=type==='vertex'?'vertex-icon':'edge-icon';ui.ghostText.textContent=type==='vertex'?'頂點':'稜';moveGhost(e.clientX,e.clientY);window.addEventListener('pointermove',onToolMove);window.addEventListener('pointerup',endToolDrag,{once:true})}
function onToolMove(e){if(!toolDrag)return;moveGhost(e.clientX,e.clientY);const r=renderer.domElement.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){toolDrag.candidate=null;clearSnapVisual();return}if(toolDrag.type==='vertex'){const c=candidateForNewVertex(e.clientX,e.clientY);toolDrag.candidate=c;if(c)showVertexSnap(c)}else{const c=candidateForEdge(e.clientX,e.clientY);toolDrag.candidate=c;if(c)showEdgeSnap(c)}}
function endToolDrag(e){window.removeEventListener('pointermove',onToolMove);ui.ghost.classList.remove('show','snap');controls.enabled=true;if(!toolDrag)return;const {type,candidate}=toolDrag;toolDrag=null;clearSnapVisual();if(!candidate){showToast('請將零件拖入圖格');return}if(type==='vertex'){if(candidate.type==='existing'){selectVertex(candidate.existing);showToast('已選取最近的頂點');return}const v=createVertex(candidate.position);if(candidate.source&&!edgeExists(candidate.source,v))createEdge(candidate.source,v);selectVertex(v);showToast(candidate.source?'頂點已自動吸附並連接':'已放置頂點');return}let a=candidate.a||createVertex(candidate.aPos),b=candidate.b||createVertex(candidate.bPos);const edge=createEdge(a,b);if(edge){selectEdge(edge);showToast('稜已自動吸附連接')}else showToast('這個位置已有稜')}
document.querySelectorAll('[data-tool]').forEach(el=>el.addEventListener('pointerdown',e=>startToolDrag(e,el.dataset.tool)));

renderer.domElement.addEventListener('pointerdown',e=>{const obj=pickObject(e.clientX,e.clientY);if(!obj){objectDrag={kind:'orbit',x:e.clientX,y:e.clientY,moved:false};return}e.preventDefault();controls.enabled=false;if(obj.userData.kind==='vertex'){const v=obj;objectDrag={kind:'vertex',item:v,x:e.clientX,y:e.clientY,moved:false,original:v.position.clone(),layer:Math.round((v.position.y-BASE_Y)/STEP),candidate:null};}else{const edge=obj.userData.edge;objectDrag={kind:'edge',item:edge,x:e.clientX,y:e.clientY,moved:false,candidate:null};edge.mesh.material.transparent=true;edge.mesh.material.opacity=.25;}});
renderer.domElement.addEventListener('pointermove',e=>{if(!objectDrag||objectDrag.kind==='orbit')return;const moved=Math.hypot(e.clientX-objectDrag.x,e.clientY-objectDrag.y);if(moved>5)objectDrag.moved=true;if(!objectDrag.moved)return;if(objectDrag.kind==='vertex'){const c=candidateForVertex(objectDrag.item,e.clientX,e.clientY,objectDrag.layer);objectDrag.candidate=c;if(c){objectDrag.item.position.copy(c.position);edges.forEach(updateEdge);showVertexSnap(c)}}else{const c=candidateForEdge(e.clientX,e.clientY,objectDrag.item);objectDrag.candidate=c;if(c)showEdgeSnap(c)}});
renderer.domElement.addEventListener('pointerup',e=>{if(!objectDrag)return;const d=objectDrag;objectDrag=null;if(d.kind==='orbit')return;controls.enabled=true;clearSnapVisual();if(d.kind==='vertex'){if(!d.moved){selectVertex(d.item);return}const c=d.candidate;if(!c){d.item.position.copy(d.original);edges.forEach(updateEdge);showToast('未找到合適連接位置');return}let result=d.item;if(c.type==='merge'){result=mergeVertices(d.item,c.merge)}else{d.item.position.copy(c.position);if(c.source&&!edgeExists(c.source,d.item))createEdge(c.source,d.item)}edges.forEach(updateEdge);selectVertex(result);showToast(c.type==='free'?'頂點已移到格點':'頂點已自動吸附連接');return}d.item.mesh.material.opacity=1;d.item.mesh.material.transparent=false;if(!d.moved){selectEdge(d.item);return}const c=d.candidate;if(!c){showToast('未找到合適連接位置');selectEdge(d.item);return}let a=c.a||createVertex(c.aPos),b=c.b||createVertex(c.bPos);if(edgeExists(a,b,d.item)){showToast('這個位置已有稜');selectEdge(d.item);return}d.item.a=a;d.item.b=b;updateEdge(d.item);selectEdge(d.item);showToast('稜已自動轉移並連接')});
renderer.domElement.addEventListener('pointercancel',()=>{if(objectDrag?.kind==='vertex')objectDrag.item.position.copy(objectDrag.original);if(objectDrag?.kind==='edge'){objectDrag.item.mesh.material.opacity=1;objectDrag.item.mesh.material.transparent=false}objectDrag=null;controls.enabled=true;clearSnapVisual();edges.forEach(updateEdge)});

document.getElementById('layerUp').onclick=()=>{currentLayer=Math.min(MAX_LAYER-1,currentLayer+1);updateUI();showToast(`現在放置在第 ${currentLayer+1} 層`)};
document.getElementById('layerDown').onclick=()=>{currentLayer=Math.max(0,currentLayer-1);updateUI();showToast(`現在放置在第 ${currentLayer+1} 層`)};
document.getElementById('moveUpBtn').onclick=()=>moveSelectedLayer(1);document.getElementById('moveDownBtn').onclick=()=>moveSelectedLayer(-1);document.getElementById('deleteBtn').onclick=deleteSelected;document.getElementById('resetViewBtn').onclick=resetView;

function addGuideEdge(a,b,mat){const d=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,1,10),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.scale.set(1,d.length(),1);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());guideGroup.add(m)}
function showGuide(type){while(guideGroup.children.length){const c=guideGroup.children.pop();c.geometry?.dispose();c.material?.dispose()}if(type==='none')return;const x=type==='cube'?2:4,z=2,y0=BASE_Y,y1=BASE_Y+STEP;const pts=[[-x,y0,-z],[x,y0,-z],[x,y0,z],[-x,y0,z],[-x,y1,-z],[x,y1,-z],[x,y1,z],[-x,y1,z]].map(p=>new THREE.Vector3(...p));const vm=new THREE.MeshBasicMaterial({color:0x60a5fa,transparent:true,opacity:.2,depthWrite:false}),em=new THREE.MeshBasicMaterial({color:0x60a5fa,transparent:true,opacity:.2,depthWrite:false});pts.forEach(p=>{const s=new THREE.Mesh(new THREE.SphereGeometry(.22,16,12),vm.clone());s.position.copy(p);guideGroup.add(s)});[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]].forEach(([a,b])=>addGuideEdge(pts[a],pts[b],em.clone()))}
document.getElementById('guideSelect').onchange=e=>{showGuide(e.target.value);showToast(e.target.value==='none'?'已關閉導引':'已顯示淡色導引')};

function componentsCount(){const seen=new Set();let n=0;for(const v of vertices){if(seen.has(v))continue;n++;const stack=[v];seen.add(v);while(stack.length){const cur=stack.pop();for(const e of edges){const next=e.a===cur?e.b:e.b===cur?e.a:null;if(next&&!seen.has(next)){seen.add(next);stack.push(next)}}}}return n}
function analyse(){const degree=new Map(vertices.map(v=>[v,0]));edges.forEach(e=>{degree.set(e.a,(degree.get(e.a)||0)+1);degree.set(e.b,(degree.get(e.b)||0)+1)});const values=vertices.map(v=>degree.get(v)||0).sort((a,b)=>a-b),levels=new Set(vertices.map(v=>v.position.y)).size,parts=componentsCount();let name='自由創作模型',message='模型以水平、前後或垂直稜連接。';if(!vertices.length){name='模型仍是空白';message='先由零件盒拖出頂點和稜。'}else if(parts>1){name='模型有未連接部分';message=`目前有 ${parts} 個分開部分，可將零件拖近綠色位置自動連接。`}else if(vertices.length===8&&edges.length===12&&values.every(v=>v===3)){const xs=[...new Set(vertices.map(v=>v.position.x))],zs=[...new Set(vertices.map(v=>v.position.z))];name=(xs.length===2&&zs.length===2&&Math.abs(xs[1]-xs[0])===Math.abs(zs[1]-zs[0]))?'可能是正方體框架':'可能是長方體框架';message='共有8個頂點、12條稜，每個頂點連接3條稜。'}else if(vertices.length===4&&edges.length===4&&values.every(v=>v===2)){name='可能是正方形或長方形框架';message='共有4個頂點和4條稜。'}return{degree,levels,parts,name,message}}
function showData(){const r=analyse();document.getElementById('resultVertices').textContent=vertices.length;document.getElementById('resultEdges').textContent=edges.length;document.getElementById('resultLevels').textContent=r.levels;document.getElementById('resultParts').textContent=r.parts;document.getElementById('shapeName').textContent=r.name;document.getElementById('shapeMessage').textContent=r.message;document.getElementById('detail').innerHTML=vertices.length?'<b>每個頂點連接的稜：</b><br>'+vertices.map(v=>`頂點 ${v.userData.id}：${r.degree.get(v)||0} 條`).join('　 '):'尚未有模型資料。';document.getElementById('dataModal').classList.add('show')}
document.getElementById('finishBtn').onclick=showData;document.getElementById('continueBtn').onclick=()=>document.getElementById('dataModal').classList.remove('show');document.getElementById('clearBtn').onclick=()=>{document.getElementById('dataModal').classList.remove('show');clearAll();resetView()};document.getElementById('helpBtn').onclick=()=>document.getElementById('helpModal').classList.add('show');document.getElementById('closeHelpBtn').onclick=()=>document.getElementById('helpModal').classList.remove('show');document.getElementById('dataModal').onclick=e=>{if(e.target.id==='dataModal')e.currentTarget.classList.remove('show')};document.getElementById('helpModal').onclick=e=>{if(e.target.id==='helpModal')e.currentTarget.classList.remove('show')};
function animate(){requestAnimationFrame(animate);controls.update();edges.forEach(updateEdge);const pulse=1+Math.sin(performance.now()*.008)*.1;snapHaloA.scale.setScalar(pulse);snapHaloB.scale.setScalar(pulse);renderer.render(scene,camera)}animate();updateUI();