const interactables=[];
function buildShop(id){const inf=SHOP_INFO[id],p=inf.pos;const g=new THREE.Group();g.position.copy(p);g.userData.shopId=id;g.userData.shopBaseY=p.y;g.userData.phase=Object.keys(SHOP_INFO).indexOf(id)*1.3;
  const bodyMat=new THREE.MeshStandardMaterial({color:inf.color,roughness:.76});
  const base=new THREE.Mesh(new THREE.BoxGeometry(7.7,.35,5.9),new THREE.MeshStandardMaterial({color:0xd8c5a0,roughness:1}));base.position.y=.18;base.receiveShadow=true;g.add(base);
  const body=new THREE.Mesh(new THREE.BoxGeometry(7.2,4.7,5.5),bodyMat);body.position.y=2.35;body.castShadow=body.receiveShadow=true;g.add(body);
  const roofMain=new THREE.Mesh(new THREE.BoxGeometry(8.0,.45,6.1),new THREE.MeshStandardMaterial({color:0xa96b45,roughness:.9}));roofMain.position.y=5.15;roofMain.castShadow=true;g.add(roofMain);
  const roofTop=new THREE.Mesh(new THREE.BoxGeometry(7.1,.35,5.1),new THREE.MeshStandardMaterial({color:0xc78b5f,roughness:.9}));roofTop.position.y=5.48;roofTop.castShadow=true;g.add(roofTop);
  const fascia=new THREE.Mesh(new THREE.BoxGeometry(7.6,.96,.72),new THREE.MeshStandardMaterial({color:0xfff1c7,roughness:.8}));fascia.position.set(0,4.32,3.0);fascia.castShadow=true;g.add(fascia);
  for(let i=0;i<7;i++){const aw=new THREE.Mesh(new THREE.BoxGeometry(1.02,.24,1.42),new THREE.MeshStandardMaterial({color:i%2?0xfff8e5:inf.color,roughness:.75}));aw.position.set(-3.05+i*1.02,3.72,3.24);aw.rotation.x=-.26;aw.castShadow=true;g.add(aw)}
  const awningFront=new THREE.Mesh(new THREE.BoxGeometry(7.25,.18,.22),new THREE.MeshStandardMaterial({color:0xfff8e5,roughness:.85}));awningFront.position.set(0,3.46,4.02);g.add(awningFront);
  const doorFrame=new THREE.Mesh(new THREE.BoxGeometry(1.9,2.95,.26),new THREE.MeshStandardMaterial({color:0xffeccf,roughness:.85}));doorFrame.position.set(0,1.48,2.78);g.add(doorFrame);
  const door=new THREE.Mesh(new THREE.BoxGeometry(1.45,2.55,.18),new THREE.MeshStandardMaterial({color:0x6a4531,roughness:.8}));door.position.set(0,1.28,2.86);g.add(door);
  const glassDoor=new THREE.Mesh(new THREE.BoxGeometry(1.18,2.18,.06),new THREE.MeshStandardMaterial({color:0xbfeeff,transparent:true,opacity:.58,metalness:.12,roughness:.12}));glassDoor.position.set(0,1.34,2.97);g.add(glassDoor);
  [-2.35,2.35].forEach((x,wi)=>{const sill=new THREE.Mesh(new THREE.BoxGeometry(2.05,.18,.35),new THREE.MeshStandardMaterial({color:0xe5d3b5,roughness:.85}));sill.position.set(x,1.48,2.92);g.add(sill);const frame=new THREE.Mesh(new THREE.BoxGeometry(2.0,1.95,.22),new THREE.MeshStandardMaterial({color:0xfff1ce,roughness:.8}));frame.position.set(x,2.38,2.81);g.add(frame);const win=new THREE.Mesh(new THREE.BoxGeometry(1.68,1.62,.10),new THREE.MeshStandardMaterial({color:0xb8eaff,transparent:true,opacity:.62,metalness:.12,roughness:.12}));win.position.set(x,2.38,2.95);g.add(win);for(let r=0;r<2;r++)for(let c=0;c<3;c++){const item=new THREE.Mesh(new THREE.BoxGeometry(.34,.40,.12),new THREE.MeshStandardMaterial({color:[0xffd04f,0xf26d6d,0x64c8e5,0x78c86a,0xff9fc9][(r*3+c+wi)%5]}));item.position.set(x-.50+c*.50,2.03+r*.58,3.06);g.add(item)}for(let s=0;s<2;s++){const frameBar=new THREE.Mesh(new THREE.BoxGeometry(.08,1.68,.03),new THREE.MeshStandardMaterial({color:0xdcc7a3}));frameBar.position.set(x+(s?-.28:.28),2.38,3.0);g.add(frameBar)}});
  [-3.45,3.45].forEach((x,i)=>{const pot=new THREE.Mesh(new THREE.CylinderGeometry(.33,.42,.55,12),new THREE.MeshStandardMaterial({color:0xbd6f42}));pot.position.set(x,.28,3.15);g.add(pot);for(let k=0;k<4;k++){const fl=new THREE.Mesh(new THREE.SphereGeometry(.16,10,8),new THREE.MeshStandardMaterial({color:[0xffdf58,0xff79a6,0xffffff,0x9b76e8][(i+k)%4]}));fl.position.set(x+(k-1.5)*.16,.72+.05*(k%2),3.15+(k%2)*.10);g.add(fl)}const leaf=new THREE.Mesh(new THREE.IcosahedronGeometry(.22,0),new THREE.MeshStandardMaterial({color:0x4f9d5d,roughness:1}));leaf.position.set(x,.66,3.12);g.add(leaf)});
  const signDeco=new THREE.Mesh(new THREE.SphereGeometry(.20,12,10),new THREE.MeshStandardMaterial({color:inf.color}));signDeco.position.set(0,4.85,3.16);g.add(signDeco);
  scene.add(g);const lab=labelPlane(`${inf.emoji} ${inf.name}`,p.x,6.92,p.z+2.95,'#fff7dc');lab.userData.faceCamera=true;lab.userData.shopLabel=true;lab.userData.baseY=lab.position.y;lab.userData.phase=g.userData.phase;
  interactables.push({type:'shop',id,pos:new THREE.Vector3(p.x,0,p.z+4.2),label:`進入${inf.name}`});
}
Object.keys(SHOP_INFO).forEach(buildShop);
const animatedClouds=[];
function makeCloud(x,y,z,s=1){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1,transparent:true,opacity:.92});[[0,0,0,1.0],[-.85,-.08,.05,.72],[.85,-.06,0,.78],[-.20,.38,.02,.72],[.38,.34,.04,.62]].forEach(p=>{const m=new THREE.Mesh(new THREE.SphereGeometry(p[3],14,10),mat);m.position.set(p[0],p[1],p[2]);m.scale.set(1.25,.72,1);g.add(m)});g.position.set(x,y,z);g.scale.setScalar(s);g.userData.speed=.22+Math.random()*.12;g.userData.startX=x;scene.add(g);animatedClouds.push(g)}
makeCloud(-18,16,-30,1.5);makeCloud(8,13,-36,1.1);makeCloud(24,18,-26,1.35);
const butterflies=[];
function makeButterfly(x,y,z,color=0xff7aac){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.025,.12,3,6),new THREE.MeshStandardMaterial({color:0x3b332d}));body.rotation.z=Math.PI/2;g.add(body);const wingMat=new THREE.MeshStandardMaterial({color,side:THREE.DoubleSide,roughness:.65});const left=new THREE.Mesh(new THREE.CircleGeometry(.13,12),wingMat);left.position.x=-.08;left.rotation.y=.45;g.add(left);const right=left.clone();right.position.x=.08;right.rotation.y=-.45;g.add(right);g.position.set(x,y,z);g.userData.wings=[left,right];g.userData.origin=new THREE.Vector3(x,y,z);g.userData.phase=Math.random()*Math.PI*2;scene.add(g);butterflies.push(g)}
makeButterfly(-8,1.1,4,0xff7aac);makeButterfly(7,1.25,7,0x8f75e8);makeButterfly(-12,1.3,-3,0xffd24d);makeButterfly(12,1.15,-1,0x65b9ff);
const birds=[];
function makeBird(x,y,z,s=.5){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0x42576a,roughness:.8,side:THREE.DoubleSide});const l=new THREE.Mesh(new THREE.PlaneGeometry(.7,.18),mat);l.position.x=-.30;l.rotation.z=.15;g.add(l);const r=l.clone();r.position.x=.30;r.rotation.z=-.15;g.add(r);g.position.set(x,y,z);g.scale.setScalar(s);g.userData.wings=[l,r];g.userData.phase=Math.random()*6;g.userData.radius=10+Math.random()*4;scene.add(g);birds.push(g)}
makeBird(0,13,-20,.65);makeBird(7,15,-24,.52);
