if(!window.THREE){alert('未能載入 3D 程式庫，請檢查網絡連線後重新整理。');throw new Error('Three.js 未能載入')}
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fd8ff);scene.fog=new THREE.Fog(0xc7ecff,42,86);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,120);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('game').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x557a45,2.4));
const sun=new THREE.DirectionalLight(0xfff4d4,3.2);sun.position.set(-18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-38;sun.shadow.camera.right=38;sun.shadow.camera.top=38;sun.shadow.camera.bottom=-38;scene.add(sun);
const fillLight=new THREE.DirectionalLight(0xcfefff,1.0);fillLight.position.set(18,16,-12);scene.add(fillLight);
const ambientSparkle=new THREE.PointLight(0xfff3dd,.8,60);ambientSparkle.position.set(0,10,0);scene.add(ambientSparkle);
const skyDome=new THREE.Mesh(new THREE.SphereGeometry(95,32,20),new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:{topColor:{value:new THREE.Color(0x6ec1ff)},bottomColor:{value:new THREE.Color(0xeef9ff)}},vertexShader:`varying vec3 vWorldPosition; void main(){ vec4 worldPosition = modelMatrix * vec4(position,1.0); vWorldPosition = worldPosition.xyz; gl_Position = projectionMatrix * modelViewMatrix * vec4(position,1.0); }`,fragmentShader:`uniform vec3 topColor; uniform vec3 bottomColor; varying vec3 vWorldPosition; void main(){ float h = normalize(vWorldPosition + vec3(0.0,20.0,0.0)).y; gl_FragColor = vec4(mix(bottomColor, topColor, max(pow(max(h,0.0),0.75),0.0)), 1.0); }`}));scene.add(skyDome);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(74,74),new THREE.MeshStandardMaterial({color:0x7cc768,roughness:.98}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
function box(w,h,d,color,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);return m}
box(6,.05,60,0xe9d7b8,0,.03,0);box(60,.05,6,0xe9d7b8,0,.035,0);
for(let i=-28;i<=28;i+=2){for(let j=-2;j<=2;j+=2){const paver=new THREE.Mesh(new THREE.BoxGeometry(1.6,.03,1.6),new THREE.MeshStandardMaterial({color:(i+j)%4===0?0xe8d5b4:0xf2e3c6,roughness:.98}));paver.position.set(j,.04,i);paver.receiveShadow=true;scene.add(paver)}}
for(let i=-28;i<=28;i+=2){for(let j=-2;j<=2;j+=2){const paver=new THREE.Mesh(new THREE.BoxGeometry(1.6,.03,1.6),new THREE.MeshStandardMaterial({color:(i+j)%4===0?0xe8d5b4:0xf2e3c6,roughness:.98}));paver.position.set(i,.04,j);paver.receiveShadow=true;scene.add(paver)}}
const plaza=new THREE.Mesh(new THREE.CylinderGeometry(7.4,7.4,.08,48),new THREE.MeshStandardMaterial({color:0xf3e2c3,roughness:.98}));plaza.position.y=.04;plaza.receiveShadow=true;scene.add(plaza);
const plazaTrim=new THREE.Mesh(new THREE.TorusGeometry(7.42,.10,10,64),new THREE.MeshStandardMaterial({color:0xd4bf99,roughness:.8}));plazaTrim.rotation.x=Math.PI/2;plazaTrim.position.y=.08;scene.add(plazaTrim);
const pond=new THREE.Mesh(new THREE.CylinderGeometry(3.35,3.35,.25,40),new THREE.MeshStandardMaterial({color:0x58bada,metalness:.16,roughness:.22}));pond.position.set(0,.1,10);pond.receiveShadow=true;scene.add(pond);
const pondInner=new THREE.Mesh(new THREE.CylinderGeometry(2.5,2.5,.15,36),new THREE.MeshStandardMaterial({color:0x89dcf0,transparent:true,opacity:.85,roughness:.12}));pondInner.position.set(0,.22,10);scene.add(pondInner);
function tree(x,z,s=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.24*s,.34*s,2.3*s,12),new THREE.MeshStandardMaterial({color:0x8a5531,roughness:1}));trunk.position.y=1.15*s;trunk.castShadow=true;g.add(trunk);[[-.75,2.8,0,.95],[.78,2.7,.1,.88],[0,3.15,0,1.05],[.18,2.5,.72,.82],[-.25,2.45,-.68,.78]].forEach((p,i)=>{const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(p[3]*s,2),new THREE.MeshStandardMaterial({color:[0x48a85f,0x5ab56c,0x3f9653][i%3],roughness:1}));crown.position.set(p[0]*s,p[1]*s,p[2]*s);crown.castShadow=true;g.add(crown)});g.position.set(x,0,z);scene.add(g)}
function shrub(x,z,s=.55,c=0x59aa61){const b=new THREE.Mesh(new THREE.SphereGeometry(.55*s,12,10),new THREE.MeshStandardMaterial({color:c,roughness:1}));b.position.set(x,.28,z);b.scale.set(1.2,.8,1);b.castShadow=true;scene.add(b)}
[[-22,-18],[-22,-5],[-22,17],[22,-17],[22,-2],[22,18],[-7,21],[7,21],[-7,-21],[7,-21],[-19,3],[19,4],[-13,14],[13,-14]].forEach((p,i)=>tree(p[0],p[1],.92+(i%3)*.12));
[[-16,-12],[-15,-10],[-12,15],[13,16],[15,-12],[16,-10],[-5,16],[5,16],[-5,-16],[5,-16]].forEach((p,i)=>shrub(p[0],p[1],.75,[0x63b66a,0x78c77d,0x54aa63][i%3]));
function bench(x,z,rot=0){const g=new THREE.Group();const wood=new THREE.MeshStandardMaterial({color:0xa8683c,roughness:.9});for(let i=0;i<3;i++){const slat=new THREE.Mesh(new THREE.BoxGeometry(2.9,.10,.18),wood);slat.position.set(0,.72,.20-i*.18);g.add(slat)}for(let i=0;i<3;i++){const slat=new THREE.Mesh(new THREE.BoxGeometry(2.9,.10,.18),wood);slat.position.set(0,1.02+i*.18,.28);g.add(slat)}[-1.2,1.2].forEach(px=>{const leg=new THREE.Mesh(new THREE.BoxGeometry(.18,.82,.55),new THREE.MeshStandardMaterial({color:0x33433b,roughness:.8}));leg.position.set(px,.42,0);g.add(leg)});g.position.set(x,0,z);g.rotation.y=rot;g.traverse(o=>{if(o.isMesh)o.castShadow=true;o.receiveShadow=true});scene.add(g)}
bench(-7,5,Math.PI/2);bench(7,-5,-Math.PI/2);
function lampPost(x,z){const g=new THREE.Group();const pole=new THREE.Mesh(new THREE.CylinderGeometry(.08,.10,3.3,12),new THREE.MeshStandardMaterial({color:0x2f3538,roughness:.78}));pole.position.y=1.65;g.add(pole);const arm=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.7),pole.material);arm.position.set(0,3.05,.26);g.add(arm);const lantern=new THREE.Mesh(new THREE.BoxGeometry(.46,.62,.46),new THREE.MeshStandardMaterial({color:0x3d4347,roughness:.8}));lantern.position.set(0,2.66,.48);g.add(lantern);const glow=new THREE.Mesh(new THREE.BoxGeometry(.28,.42,.28),new THREE.MeshStandardMaterial({color:0xffefc0,emissive:0xffe9a8,emissiveIntensity:.65,roughness:.35}));glow.position.set(0,2.66,.48);g.add(glow);g.position.set(x,0,z);g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g)}
lampPost(-9.5,-4.2);lampPost(9.5,-4.0);lampPost(-8.8,12.8);lampPost(8.8,12.8);
function mapBoard(x,z){const g=new THREE.Group();const frameMat=new THREE.MeshStandardMaterial({color:0x96603a,roughness:.88});[-.9,.9].forEach(px=>{const post=new THREE.Mesh(new THREE.BoxGeometry(.18,1.9,.18),frameMat);post.position.set(px,.95,0);g.add(post)});const board=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.45,.12),new THREE.MeshStandardMaterial({color:0xe7d5ab,roughness:.9}));board.position.set(0,1.55,0);g.add(board);const map=new THREE.Mesh(new THREE.PlaneGeometry(1.95,1.05),new THREE.MeshStandardMaterial({color:0xcdecb8}));map.position.set(0,1.55,.08);g.add(map);g.position.set(x,0,z);g.rotation.y=-.55;g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);const sign=labelPlane('公園地圖',x,2.7,z,'#f7e7c6');sign.scale.set(.45,.45,.45);sign.userData.faceCamera=true}
function flowerPatch(x,z,count=10){for(let i=0;i<count;i++){const a=i/count*Math.PI*2,r=.30+(i%4)*.18;const stem=new THREE.Mesh(new THREE.CylinderGeometry(.02,.03,.36,6),new THREE.MeshStandardMaterial({color:0x36854a}));stem.position.set(x+Math.cos(a)*r,.18,z+Math.sin(a)*r);scene.add(stem);const core=new THREE.Mesh(new THREE.SphereGeometry(.05,8,6),new THREE.MeshStandardMaterial({color:0xffd34b}));core.position.set(stem.position.x,.43,stem.position.z);scene.add(core);for(let p=0;p<5;p++){const petal=new THREE.Mesh(new THREE.SphereGeometry(.05,8,6),new THREE.MeshStandardMaterial({color:[0xff7ca7,0xffffff,0x9b76e8,0xffc85f][(i+p)%4]}));petal.scale.set(1.2,.7,1.2);petal.position.set(stem.position.x+Math.cos(p*Math.PI*2/5)*.07,.43,stem.position.z+Math.sin(p*Math.PI*2/5)*.07);scene.add(petal)}}}
mapBoard(14.6,10.8);[[-9,-2],[9,2],[-8,15],[8,-15],[-17,0],[17,0],[-14,10],[14,-10],[-10,18],[10,-18]].forEach((p,i)=>flowerPatch(p[0],p[1],10+(i%3)*2));
function balloonCluster(x,z){const cols=[0xff5577,0x55aaff,0xffd34e,0x8d70e8];cols.forEach((c,i)=>{const b=new THREE.Mesh(new THREE.SphereGeometry(.34,14,10),new THREE.MeshStandardMaterial({color:c,roughness:.45}));b.scale.y=1.22;b.position.set(x+(i-1.5)*.33,2.4+(i%2)*.35,z);b.userData.balloonBase=b.position.y;scene.add(b);const line=new THREE.Mesh(new THREE.CylinderGeometry(.012,.012,2.0,5),new THREE.MeshBasicMaterial({color:0x666666}));line.position.set(b.position.x,1.25,z);scene.add(line)})}
balloonCluster(-18,9);balloonCluster(-17,11);
const rim=new THREE.Mesh(new THREE.TorusGeometry(3.2,.28,14,56),new THREE.MeshStandardMaterial({color:0xf0f2e9,roughness:.65}));rim.rotation.x=Math.PI/2;rim.position.set(0,.34,10);rim.castShadow=true;scene.add(rim);
const midBasin=new THREE.Mesh(new THREE.CylinderGeometry(1.2,1.45,.18,24),new THREE.MeshStandardMaterial({color:0xf2f5ef,roughness:.7}));midBasin.position.set(0,.78,10);midBasin.castShadow=true;scene.add(midBasin);
const column=new THREE.Mesh(new THREE.CylinderGeometry(.28,.38,1.25,18),new THREE.MeshStandardMaterial({color:0xf4f6f0,roughness:.7}));column.position.set(0,1.25,10);column.castShadow=true;scene.add(column);
const topBowl=new THREE.Mesh(new THREE.CylinderGeometry(.58,.78,.16,18),new THREE.MeshStandardMaterial({color:0xf5f7f2,roughness:.65}));topBowl.position.set(0,1.95,10);topBowl.castShadow=true;scene.add(topBowl);
const fountainJet=new THREE.Mesh(new THREE.CylinderGeometry(.06,.12,2.3,10),new THREE.MeshStandardMaterial({color:0x9fe8ff,transparent:true,opacity:.74,roughness:.18}));fountainJet.position.set(0,2.2,10);fountainJet.userData.fountainMain=true;scene.add(fountainJet);
[-1,1].forEach(ix=>[-1,1].forEach(iz=>{const sideJet=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,1.0,8),new THREE.MeshStandardMaterial({color:0xb6efff,transparent:true,opacity:.62,roughness:.12}));sideJet.position.set(ix*1.25,.95,10+iz*1.25);sideJet.rotation.z=.25*ix;sideJet.userData.fountainSide=true;sideJet.userData.phase=ix*2+iz;scene.add(sideJet)}));
function makeTextTexture(text,bg='#ffffff',fg='#17362a',w=512,h=160){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.roundRect(5,5,w-10,h-10,28);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.25)';ctx.lineWidth=8;ctx.stroke();ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 62px sans-serif';ctx.fillText(text,w/2,h/2+2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function labelPlane(text,x,y,z,bg){const mat=new THREE.MeshBasicMaterial({map:makeTextTexture(text,bg),transparent:true,side:THREE.DoubleSide});const p=new THREE.Mesh(new THREE.PlaneGeometry(4.8,1.5),mat);p.position.set(x,y,z);scene.add(p);return p}
